# Generated by Django 5.2.2 on 2025-06-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0002_prato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='tempo_preparo',
            field=models.IntegerField(),
        ),
    ]
