# Generated by Django 5.2.2 on 2025-07-05 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0004_prato_funcionario'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario'),
        ),
    ]
